### Create

POST {{u}}/users
Content-Type: application/json

{
  "firstName": "Hamda",
  "lastName": "H",
  "date_of_birth": "1990-01-01",
  "gender": "M",
  "email": "john@example.com",
  "role": "ADMIN",
  "username": "hamda",
  "password": "hamada@12"
}

> {%
    res = response.body
    const {user} = res
    client.log(res)

    if (res._id)
        client.global.set("adminId", user._id)
    client.global.set("admin", user)

%}


### Delete
DELETE {{u}}/users/{{adminId}}
