### Create User with role of Mentor

POST {{u}}/users
Content-Type: application/json

{
  "firstName": "Mentor",
  "lastName": "User",
  "date_of_birth": "1988-02-10",
  "gender": "M",
  "email": "mentor@example.com",
  "role": "MENTOR",
  "username": "mentoruser",
  "password": "mentorpassword"
}

> {%
    res = response.body
    const {user} = res

    client.global.set("mentorUserId", user._id)
    client.global.set("mentorUser", user)


    client.test("res", () => {
        client.assert(response.status == 200, "mentor user created")
    })
%}

### Create Mentor

POST {{u}}/mentors/{{mentorUserId}}
Content-Type: application/json

{
  "exp": 5,
  "subjectName": "MATH"
}

> {%
    res = response.body
    const user = res

    client.global.set("mentorId", user._id)
    client.global.set("mentor", user)


    client.test("res", () => {
        client.assert(response.status == 200, "mentor created")
    })
%}

### Update Mentor
PUT {{u}}/mentors/{{mentorId}}
Content-Type: application/json

{
  "exp": 14,
  "subjectName": "HISTORY"
}

###



