### Create

POST {{u}}/users
Content-Type: application/json

{
  "firstName": "Mentor",
  "lastName": "User",
  "date_of_birth": "1988-02-10",
  "gender": "M",
  "email": "mentor@example.com",
  "role": "MENTOR",
  "username": "mentoruser",
  "password": "mentorpassword"
}

> {%
    res = response.body

    client.global.set("mentorId", res._id)
    client.global.set("mentor", res)


    client.test("res", () => {
        client.assert(response.status == 201, "mentor created")
    })
%}

