### Create User with role of Teacher

POST {{u}}/users
Content-Type: application/json

{
  "firstName": "Tadashi",
  "lastName": "Hamada",
  "date_of_birth": "1990-08-25",
  "gender": "F",
  "email": "teacher@example.com",
  "role": "TEACHER",
  "username": "hamada",
  "password": "hamada@123"
}

> {%
    res = response.body
    const {user} = res
    client.log(JSON.stringify(user))

    client.global.set("teacherUserId", user._id)
    client.global.set("teacherUser", user)


    client.test("res", () => {
        client.assert(response.status == 200, "teacher user created")
    })
%}

### Add User to Teachers

POST http://localhost:1606/teachers/{{teacherUserId}}
Content-Type: application/json

{
  "exp": 5,
  "subjectName": "MATH"
}

> {%
    res = response.body
    const user = res

    client.global.set("teacherId", user._id)
    client.global.set("teacher", user)


    client.test("res", () => {
        client.assert(response.status == 200, "teacher user created")
    })
%}

###


